### PR TITLE
Quiet the aziot-edged.service log "Watchdog checking..." "Edge runtime is running", and "Querying system resources..." messages. (#5700)

### PR DESCRIPTION
**Pull request by robinmholt-daikin**
Currently, the messages modified by this commit frequently get added to the system log at the default INFO level.  Reduce these to DEBUG level to quiet the logs.

```bash
Dec 27 21:03:20 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:20Z [INFO] - Watchdog checking Edge runtime status
Dec 27 21:03:20 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:20Z [INFO] - Edge runtime is running
Dec 27 21:03:21 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:21Z [INFO] - <-- GET /systeminfo/resources?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:21 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:21Z [INFO] - Querying system resources...
Dec 27 21:03:22 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:22Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:26 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:26Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:26 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:26Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:31 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:31Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:31 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:31Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:36 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:36Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:36 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:36Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:41 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:41Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:41 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:41Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:46 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:46Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:46 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:46Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:51 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:51Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:51 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:51Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:03:56 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:56Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:03:56 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:03:56Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:04:01 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:01Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:04:01 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:01Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:04:06 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:06Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:04:06 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:06Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:04:11 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:11Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:04:11 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:11Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:04:16 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:16Z [INFO] - <-- GET /modules?api-version=2020-07-07 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Dec 27 21:04:16 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:16Z [INFO] - --> 200 {"content-type": "application/json"}
Dec 27 21:04:20 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:20Z [INFO] - Watchdog checking Edge runtime status
Dec 27 21:04:20 SOLU424200002 aziot-edged[2546]: 2023-12-27T21:04:20Z [INFO] - Edge runtime is running

```

Since these are merely changes to logging level, I did no further testing than rebuild the package and load it onto a system.  I verified the offending log messages are no longer produced.

### CODE REVIEW

**Comment by robinmholt-daikin** [comment]
@microsoft-github-policy-service agree company="Daikin Applied, Inc."

**Comment by robinmholt-daikin** [comment]
This partially addresses https://github.com/Azure/iotedge/issues/5700

**Comment by robinmholt-daikin** [comment]
@damonbarry I see you recently committed stuff to the release/1.4 branch.  I have not found the process documentation and was wondering how I can get this type of PR making progress?

**Comment by robinmholt-daikin** [comment]
@damonbarry, looking at the PR you just completed for 1ES changes, it looks like this PR should be targetting main and then somehow a request for a cherry-pick onto release/1.4 gets handled.  Is that correct?

**Comment by damonbarry** [comment]
> @damonbarry Damon Barry FTE, looking at the PR you just completed for 1ES changes, it looks like this PR should be targetting main and then somehow a request for a cherry-pick onto release/1.4 gets handled. Is that correct?

Correct. PR gets merged to main, then my team meets regularly to consider changes that meet the bar to go into 1.4 LTS. If so, we cherry-pick to the release/1.4 branch.

**Comment by robinmholt-daikin** [comment]
Reworking this to target main.  Abandoning this PR and creating another.

**Pull request closed without merging**
