### PR TITLE
[release/1.2 cherry pick] [iotedge check] bugbash fixes (#4501)

### PR DESCRIPTION
**Pull request by daprilik**
Cherry pick into release/1.2.
Original PR for reference: #4501

### CODE REVIEW

**Comment by arsing** [comment]
Wait for all PRs to go into master first.

**Review by varunpuranik — APPROVED** [review]

**Comment by arsing** [comment]
Okay, c6a9bbb44737bac51c8945ed86bf776ef9a8279a is in. Cherry-pick it please.

**Comment by daprilik** [comment]
@arsing are you saying you want to include your bugbash fixes as part of this PR as well?

**Comment by arsing** [comment]
Yes. That's why I asked you to wait for all PRs to go in.

**Comment by daprilik** [comment]
Ahhhh, gotcha. In that case, I'll update the PR description.

**Comment by daprilik** [comment]
Whoah, I'm getting some pretty gnarly conflicts trying to cherry pick that commit, and I'm not sure why. Can you take a look?

**Comment by arsing** [comment]
cc @gordonwang0 @varunpuranik 

These are all the commits in master from us that need to be in release/1.2:

- ~~9414793823f127eef12c4c0a2313d512e05df4a1~~ (you cherry-picked in 455cef92f2945cbe08c5b5e5abb39fe5311353ff )

- d0978bf63bdd5624543680424452ee5c08fe285a

- 19a10ae1d404414b7184a176575211466515c3bf

- 66655b2558e8b602de7b0736ca59e60d92b23d51

- dc7c92944beb3747c6f5341321025c9b541056f6

- 7245c8e053b97596dd05a6c70160d4569f77bee4 (the first commit in this PR)

- c6a9bbb44737bac51c8945ed86bf776ef9a8279a

**Comment by arsing** [comment]
I pushed to https://github.com/arsing/iotedge/commits/bugbash . `reset --hard` to that.

**Comment by daprilik** [comment]
In that case, can you just open a new PR off your branch? I didn't realize we only wanted to do a single PR for all these changes, so the branch name + PR history doesn't reflect that.

Plus, it looks like the "api-proxy Checkin" issue is happening again, so maybe I'm just cursed for some reason.

**Comment by arsing** [comment]
https://github.com/Azure/iotedge/pull/4503

**Comment by daprilik** [comment]
Closing this PR in favor of #4503

Thanks Arnav

**Pull request closed without merging**
