### PR TITLE
Port missing changes from master to release/1.2

### PR DESCRIPTION
**Pull request by and-rewsmith**
Lots of test automation changes were missing from 1.2 as they were not ported over. **There were however some changes to product code that Bear and I found that weren't included in 1.2. Some of these we thought should have already been included:**

- https://github.com/Azure/iotedge/pull/4469
	- nginx changes by hugues
	- isn't currently included in 1.2. Shouldn't it be? We cherry picked this.
- https://github.com/Azure/iotedge/pull/4481
	- message pump change to edgehub core made by viktor
	- isn't currently included in 1.2. Shouldn't it be? We cherry picked this.

There were also some commits that we wanted to call out:
- https://github.com/Azure/iotedge/pull/4467
	- master was updated with this change then reverted in a later PR. 1.2 doesn't include the original commit or the revert, which makes sense. Therefore we didn't cherry pick this to 1.2.
- https://github.com/Azure/iotedge/pull/3762
	- manifest signing changes by gaya
	- shouldn't be in 1.2, right? We didn't cherry pick this.

### CODE REVIEW

**Review by ggjjj — COMMENTED** [review]
Manifest signing changes were merged after master was released to merge. It shouldn't be in 1.2

**Review by vadim-kovalyov — COMMENTED** [review]
Can't say for all of these changes, I would let others confirm, but I can confirm that #4467 is not needed, since it has problems and was reverted.

**Comment by dylanbronson** [comment]
#4490 and #4455 are not strictly needed for 1.2, and they don't touch any product code, but if you want to run long haul for 1.2 you should take them

**Comment by vipeller** [comment]
#4481 is a performance improvement, does not cause much problem if missing, but it is better to have, so thanks for merging it

**Review by huguesBouvier — APPROVED** [review]
It should be. I was waiting the result of arm32 testing. I had a PR for it actually. Thanks

**Comment by and-rewsmith** [comment]
I'm going to wait until @varunpuranik approves, then will merge

**Pull request merged**
