### PR TITLE
Move NestedEdgeEnabled out of experimental features. (#4467)

### PR DESCRIPTION
**Pull request by vadim-kovalyov**
### NOTE: After this PR is merged, Nested Edge would be enabled by default.
There are two main changes in this PR:
- Enable nested edge by default
- Move `NestedEdgeEnabled` settings out of `experimentalFeatures` section.

### Before:
To enable nested edge/broker you would need to have the following env vars in your deployment manifest:
```json
                    "edgeHub": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "edgerelease.azurecr.io/microsoft/azureiotedge-hub:1.2.0-rc3-linux-amd64",
                            "createOptions": "{\"HostConfig\": {\"PortBindings\": {\"1883/tcp\": [{\"HostPort\": \"1883\"}], \"8883/tcp\": [{\"HostPort\": \"8883\"}],\"443/tcp\": [{\"HostPort\": \"443\"}],\"5671/tcp\": [{\"HostPort\": \"5671\"}]}}}"
                        },
                        "env": {
                            "experimentalFeatures__nestedEdgeEnabled": {
                                "value": "true"
                            },
                            "experimentalFeatures__mqttBrokerEnabled": {
                                "value": "true"
                            },
                            "experimentalFeatures__enabled": {
                                "value": "true"
                            }
                        }
                    }
```

### After
With this change, the Nested Edge would be on by default. So if you want to run nested + broker, here is how the deployment manifest would look like:
```json
                    "edgeHub": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "edgerelease.azurecr.io/microsoft/azureiotedge-hub:1.2.0-rc3-linux-amd64",
                            "createOptions": "{\"HostConfig\": {\"PortBindings\": {\"1883/tcp\": [{\"HostPort\": \"1883\"}], \"8883/tcp\": [{\"HostPort\": \"8883\"}],\"443/tcp\": [{\"HostPort\": \"443\"}],\"5671/tcp\": [{\"HostPort\": \"5671\"}]}}}"
                        },
                        "env": {
                            "experimentalFeatures__mqttBrokerEnabled": {
                                "value": "true"
                            },
                            "experimentalFeatures__enabled": {
                                "value": "true"
                            }
                        }
                    }
```

if for some reason you want to disable nested edge, here's how to do that:
```json
                    "edgeHub": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "edgerelease.azurecr.io/microsoft/azureiotedge-hub:1.2.0-rc3-linux-amd64",
                            "createOptions": "{\"HostConfig\": {\"PortBindings\": {\"1883/tcp\": [{\"HostPort\": \"1883\"}], \"8883/tcp\": [{\"HostPort\": \"8883\"}],\"443/tcp\": [{\"HostPort\": \"443\"}],\"5671/tcp\": [{\"HostPort\": \"5671\"}]}}}"
                        },
                        "env": {
                            "NestedEdgeEnabled": {
                                "value": "false"
                            }
                        }
                    }
```

### CODE REVIEW

**Comment by vadim-kovalyov** [comment]
All basic test are green. I'd like to run E2E on this, but looks like they are timing out at the moment. I've also tested manually on my nested setup (L1+L2). Tested both with broker/bridge and without broker. Both scenario works, I'm able to see SimulatedTempSensor telemetry flowing. @huguesBouvier @yophilav anything else I need to try?

**Review by huguesBouvier — CHANGES_REQUESTED** [review]
The tests are not passing yet

**Comment by yophilav** [comment]
>  I'd like to run E2E on this, but looks like they are timing out at the moment

Which timeout are you referring to? If it is because of the E2E DPS tests are hanging forever, please make sure to use the `aziot.commit=9af3785447d3aee2ff83de44536906ac87fd46eb`. This will set the E2E framework to use the latest release bit of 1.2.0-rc4 which has the DPS fixes (hence passed all the tests).

**Review by varunpuranik — APPROVED** [review]

**Review by huguesBouvier — CHANGES_REQUESTED** [review]
Richard's new test is failing in it. Asking Richard to have a look.
It is working on master: https://dev.azure.com/msazure/One/_build/results?buildId=39960404&view=logs&j=e8afecc0-c259-5cc1-62e0-5c5d1c2a3db4
Approved the PR not to block it forever. Please check with Richard.

**Review by huguesBouvier — APPROVED** [review]

**Pull request merged**
