### PR TITLE
Update tokio to 1.15.0

### PR DESCRIPTION
**Pull request by lfitchett**
Fix for Component Governance

### CODE REVIEW

**Comment by arsing** [comment]
tokio 0.1.22 is still in the lockfile. IIRC the last time I'd looked into it it was a sequence of deps that were unnecessary. Can you check?

**Comment by lfitchett** [comment]
> tokio 0.1.22 is still in the lockfile. IIRC the last time I'd looked into it it was a sequence of deps that were unnecessary. Can you check?

yep, there was 1 unused reference to an old hyper proxy version

**Comment by arsing** [comment]
Your latest commit is adding in c-sdk submodules.

**Comment by lfitchett** [comment]
> Your latest commit is adding in c-sdk submodules.

yea, I fixed it. I think it's something to do with vs code's git ui keeping a reference somehow. I'm going to just delete my clone and re-clone the repo, hopefully wiping out those artifacts.

**Review by arsing — APPROVED** [review]

**Pull request merged**
