### PR TITLE
[main] Flatten additional properties of metrics

### PR DESCRIPTION
**Pull request by onalante-msft**
The recent PR for adding arbitrary device product information (#6262) changed the structure of Microsoft.Azure.Devices.Edge.Agent.Core.SystemInfo, which in turn affected the metrics sent upstream.  While it is no longer feasible with the current regime of passing through extra properties to restore the old property names verbatim, we can at least flatten the additional properties to restore the general shape of the serialized information.  There is also a new test verifying that the flattening occurs as expected.

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [x] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [x] concise summary of tests added/modified
	- [x] local testing done.

### CODE REVIEW

**Comment by micahl** [comment]
@onalante-msft is this change to have `main` contain the same changes as the `release/1.2` branch?

**Comment by onalante-msft** [comment]
Yes, it is.

**Comment by onalante-msft** [comment]
@micahl @scb01

**Review by micahl — APPROVED** [review]
lgtm

**Pull request merged**
