### PR TITLE
Fix docker-proxy startup issues

### PR DESCRIPTION
**Pull request by st3v3nmw**
This is an attempt to fix the  docker proxy issues reported in #7255 using the approaches discussed there.
The issues are:
1. If `docker-proxy.sock` already exists, `socat` fails to start. I wasn't able to reproduce this, but adding `unlink-early` to the options passed to `socat`  should remove any existing file first, see [socat's man page](https://linux.die.net/man/1/socat).
> CWunlink-early
Unlinks (removes) the file before opening it and even before applying user-early etc.
2. There's a race condition where the snap starts before docker is up and running (occurs after restarts):
```
systemd[1]: Started Service for snap application azure-iot-edge.aziot-edged.
systemd[1]: Started Service for snap application azure-iot-edge.docker-proxy.
azure-iot-edge.aziot-edged[873]: Making /var/run/iotedge if it does not exist
azure-iot-edge.aziot-edged[873]: Successfully made /var/run/iotedge if it did not exist
azure-iot-edge.aziot-edged[878]: [INFO] - Starting Azure IoT Edge Daemon
azure-iot-edge.aziot-edged[878]: [INFO] - Version - 1.5.0
azure-iot-edge.aziot-edged[878]: [INFO] - Obtaining Edge device provisioning data...
azure-iot-edge.aziot-edged[878]: [INFO] - Device is core-22-test on my-iotedge-test.azure-devices.net
azure-iot-edge.aziot-edged[878]: [INFO] - Initializing module runtime...
azure-iot-edge.aziot-edged[878]: [INFO] - Using runtime network id azure-iot-edge
azure-iot-edge.docker-proxy[1029]: 2024/07/24 12:59:59 socat[1029] E connect(5, AF=1 "/var/run/docker.sock", 22): No such file or directory
azure-iot-edge.aziot-edged[878]: [WARN] - container runtime error
azure-iot-edge.aziot-edged[878]: Caused by:
azure-iot-edge.aziot-edged[878]:     0: connection error: Connection reset by peer (os error 104)
azure-iot-edge.aziot-edged[878]:     1: Connection reset by peer (os error 104)
azure-iot-edge.aziot-edged[878]: [ERR!] - Failed to initialize module runtime: runtime operation error: initialize module runtime
systemd[1]: snap.azure-iot-edge.aziot-edged.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: snap.azure-iot-edge.aziot-edged.service: Failed with result 'exit-code'.
systemd[1]: snap.azure-iot-edge.aziot-edged.service: Consumed 2.382s CPU time.
systemd[1]: snap.azure-iot-edge.aziot-edged.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped Service for snap application azure-iot-edge.aziot-edged.
systemd[1]: snap.azure-iot-edge.aziot-edged.service: Consumed 2.382s CPU time.
```

Now, `docker-proxy` waits until docker is ready and `aziot-edged` only starts after `docker-proxy` is ready.
I was able to reproduce this issue and the logs look like this after the fix:

```
systemd[1]: Starting Service for snap application azure-iot-edge.docker-proxy...
azure-iot-edge.docker-proxy[730]: Docker socket (/var/run/docker.sock) does not exist yet. Sleeping...
azure-iot-edge.docker-proxy[730]: Docker socket (/var/run/docker.sock) does not exist yet. Sleeping...
azure-iot-edge.docker-proxy[730]: Docker socket (/var/run/docker.sock) does not exist yet. Sleeping...
azure-iot-edge.docker-proxy[730]: Docker socket (/var/run/docker.sock) does not exist yet. Sleeping...
systemd[1]: Started Service for snap application azure-iot-edge.docker-proxy.
systemd[1]: Started Service for snap application azure-iot-edge.aziot-edged.
azure-iot-edge.aziot-edged[993]: Making /var/run/iotedge if it does not exist
azure-iot-edge.aziot-edged[993]: Successfully made /var/run/iotedge if it did not exist
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:23Z [INFO] - Starting Azure IoT Edge Daemon
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:23Z [INFO] - Version - 1.5.0
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:23Z [INFO] - Obtaining Edge device provisioning data...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Device is core-22-test on my-iotedge-test.azure-devices.net
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Initializing module runtime...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Using runtime network id azure-iot-edge
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Successfully initialized module runtime
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Using existing Edge CA certificate
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Certificate aziot-edged-ca will be auto-renewed. Next renewal at 2024-10-04T12:53:53+00:00.
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Stopping all modules...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Stopping module edgeAgent...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - All modules stopped
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Detecting if device information has changed...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Device information has not changed
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting management API...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting workload API...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting new listener for module edgeAgent
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting workload API...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Stopping listener for module edgeAgent
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Workload API stopped
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting watchdog with 60 second period...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Watchdog checking Edge runtime status
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Edge runtime status is failed, starting module now...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting module edgeAgent...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting new listener for module edgeAgent
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting workload API...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:26Z [INFO] - Starting image garbage collection task...
azure-iot-edge.aziot-edged[1006]: 2024-07-25T12:39:27Z [INFO] - Started Edge runtime module edgeAgent
```

When doing local tests, make sure you're running the snap in `devmode` (because [daemon-notify](https://snapcraft.io/docs/daemon-notify-interface) won't auto-connect currently) and the snap is connected to the identity service:

```console
$ snap install azure-iot-edge_1.5.0_amd64.snap --devmode
$ snap connect azure-iot-edge:identity-service azure-iot-identity:identity-service
$ snap connect azure-iot-edge:aziotctl-executables azure-iot-identity:aziotctl-executables
$ snap set azure-iot-edge raw-config=...
```

Follow ups:
- Please make a request to the Snap Store requesting autoconnection of the daemon-notify interface. We need it to ensure `aziot-edged` starts _after_ `docker-proxy`. A `simple` daemon can't differentiate when `docker-proxy` is running or simply sleeping.

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [ ] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [ ] concise summary of tests added/modified
	- [x] local testing done.  

### Draft PRs
- Open the PR in `Draft` mode if it is:
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.

_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and%20why%20vs.%20how%20For%20example%3A%20) for the PR title and description_

### CODE REVIEW

**Comment by st3v3nmw** [comment]
@microsoft-github-policy-service agree [company="Canonical"]

**Comment by st3v3nmw** [comment]
@microsoft-github-policy-service agree company="Canonical"

**Comment by st3v3nmw** [comment]
@microsoft-github-policy-service agree company="Canonical"

**Comment by damonbarry** [comment]
@st3v3nmw The first time I tested with these changes, I flashed a raspberry pi and I forgot to install Docker first. Installation of the azure-iot-edge snap hung for several minutes until I finally got impatient and killed it. :) I wonder if the hang happened in your new socat.h code? And if so, should there be a quick check for Docker somewhere so we don't hang indefinitely?

Currently, when I install azure-iot-edge from the store without first installing docker, I get no errors. But when I do `snap connect azure-iot-edge:docker docker:docker-daemon` I will see an error (`snap "docker" is not installed`). I think that's a better experience.

**Comment by st3v3nmw** [comment]
@damonbarry, yup, I had a 5 minute timeout before failing. I've reduced it to 30 seconds.

The new behavior is:
- Check if the docker-proxy exists every 5 seconds with a 30 second timeout
- Regardless of whether the socket exists, allow the snap installation to complete
    - if the socket exists, start `docker-proxy` then `aziot-edged` in that order to avoid race conditions
    - if it doesn't, let the user fix the issue themselves.. better UX :)

**Comment by damonbarry** [comment]
@st3v3nmw With your latest changes, I confirmed install works whether I install Docker before or after IoT Edge. Of course, in the latter case, I can't successfully run `snap connect azure-iot-edge:docker docker:docker-daemon` until after Docker is installed, which is expected. 👍🏻

I'll work on getting this merged. Thanks!!

**Review by damonbarry — APPROVED** [review]

**Pull request merged**
