### PR TITLE
Fix host cpu metric incorrectly reported at 100%

### PR DESCRIPTION
**Pull request by and-rewsmith**
We made some changes to the system resource collection, where we called slightly different sysinfo apis in an attempt to optimize. This led to what I am guessing is a bug in the sysinfo crate. 

We can quickly resolve it if we roll back the commit that made these sysinfo modifications. However we should also keep the main improvement which was to set the open file descriptor limit.

### CODE REVIEW

**Review by vadim-kovalyov — APPROVED** [review]

**Comment by hugovoerman** [comment]
When will this become available? In my fleetview notebook this really looks odd. So (waiting for this to become available) I changed the CPU threshold to 110 ;)

**Comment by vadim-kovalyov** [comment]
> When will this become available? In my fleetview workbook this really looks odd. So (waiting for this to become available) I changed the CPU threshold to 110 ;)

It's already merged in 1.2 branch, so should be out with the next release, which is `1.2.4`

**Comment by hugovoerman** [comment]
And do you know WHEn this next release 1.2.4 will be available?

**Comment by vadim-kovalyov** [comment]
> And do you know when this next release 1.2.4 will be available?

@yophilav do you have any date that you can share? Thanks!

**Comment by hugovoerman** [comment]
> > And do you know when this next release 1.2.4 will be available?
> 
> @yophilav do you have any date that you can share? Thanks!

Any update perhaps?

**Comment by and-rewsmith** [comment]
@hugovoerman The current date we are eyeing is 8/25

**Comment by hugovoerman** [comment]
> @hugovoerman The current date we are eyeing is 8/25

Thank you, that would be great!

**Comment by hugovoerman** [comment]
It seems to me that something is withholding iotedge 1.2.4 to be released. Is there a new date you are eyeing for? 

And (just for my curiosity, what is withholding the release?

**Pull request merged**
