### PR TITLE
Use IS client retries

### PR DESCRIPTION
**Pull request by lfitchett**
Passes the new max_retries parameter to the IS service clients. This will allow it to retry on connection closed errors.

### CODE REVIEW

**Comment by vadim-kovalyov** [comment]
Some PR description would be nice

**Review by gordonwang0 — APPROVED** [review]
If edgelet get throttled, then won't all calls wait 1 second and try again? That leaves a high chance of everyone getting throttled again when they retry. I realize that's not what this PR is about, but it's something to link about. Maybe we should add some randomness to the retry interval.

**Comment by arsing** [comment]
We were going to put a mutex around the IS client, no? (As discussed over Teams.)

**Comment by gordonwang0** [comment]
The IS client should already have a mutex where needed. Where are you thinking of adding the mutex?

**Comment by arsing** [comment]
Right, so since it's already there, we'll basically never have a reason to retry anyway because the client will never get throttled.

**Review by arsing — APPROVED** [review]

**Comment by nimanch** [comment]
With this change, do we still need to limit EA Calls with your or Viktor's change?

**Comment by lfitchett** [comment]
The client does have a mutex, so only 1 call is sent at a time. This should make retrys rare. The main throttling will be happening in the EA change that Viktor is adding.

**Pull request merged**
