### PR TITLE
Fix build on nightly by updating c-shared dependency and removing #[m…

### PR DESCRIPTION
**Pull request by duncanfinney**
…acro_use] directives

### CODE REVIEW

**Comment by myagley** [comment]
Hey Duncan. Thanks for the PR. Do these unused `#[macro_use]` error on nightly? I'm assuming this is a Rust 2018 change?

ps- I grew up in Sterling Heights. Happy to see a fellow Michigander!

**Comment by arsing** [comment]
```
error: unused `#[macro_use]` import
  --> edgelet-utils\src\lib.rs:12:1
   |
12 | #[macro_use]
   | ^^^^^^^^^^^^
   |
note: lint level defined here
  --> edgelet-utils\src\lib.rs:3:31
   |
3  | #![deny(unused_extern_crates, warnings)]
   |                               ^^^^^^^^
   = note: #[deny(unused_imports)] implied by #[deny(warnings)]

error: aborting due to previous error
```

`use failure::Fail;` on nightly brings both the trait and the re-exported custom derive into scope as of 1.30 (a variant of the equivalent improvements for edition 2018), so the `#[macro_use]` *is* unnecessary. I'd removed a few `#[macro_use] extern crate failure_derive;` in my error messages change for the same reason, and it applies to `extern crate failure;` too.

The warning itself is new in nightly. I didn't find the PR from some searching but it does make sense for it to be a warning.

So this part of the commit LGTM.

---

There's no change to `c-shared`. Did you intend to update the `edgelet/hsm-sys/azure-iot-hsm-c/deps/c-shared` submodule reference?

**Comment by duncanfinney** [comment]
@myagley, no way! Small world. It's always cool to see Michigan people in tech. Detroit is growing quickly in the tech center too if you ever decide to come back! 

And @arsing: I realize now that I didn't include the change to c-shared on purpose. A couple of the tests need to be updated to work with the macro changes.

It took me quite a bit of finagling to get `hsm-sys` to build correctly on my machine.

The error I was getting was:
```
[ 35%] Linking C static library libaziotsharedutil.a
[ 35%] Built target aziotsharedutil

--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    use_emulator


In function ‘umocktypes_stringify_charptr.part.0’,
    inlined from ‘umocktypes_stringify_charptr’:
/home/duncan/code/iotedge2/edgelet/hsm-sys/azure-iot-hsm-c/deps/c-shared/testtools/umock-c/src/umocktypes_charptr.c:28:23: error: ‘memcpy’ forming offset 6 is out of the bounds [0, 5] [-Werror=array-bounds]
                 (void)memcpy(result, "NULL", sizeof("NULL") + 1);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘umocktypes_stringify_const_charptr.part.1’,
    inlined from ‘umocktypes_stringify_const_charptr’:
/home/duncan/code/iotedge2/edgelet/hsm-sys/azure-iot-hsm-c/deps/c-shared/testtools/umock-c/src/umocktypes_charptr.c:161:23: error: ‘memcpy’ forming offset 6 is out of the bounds [0, 5] [-Werror=array-bounds]
                 (void)memcpy(result, "NULL", sizeof("NULL") + 1);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [tests/c-shared/testtools/umock-c/CMakeFiles/umock_c.dir/build.make:193: tests/c-shared/testtools/umock-c/CMakeFiles/umock_c.dir/src/umocktypes_charptr.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1351: tests/c-shared/testtools/umock-c/CMakeFiles/umock_c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:163: all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.30/src/lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------------------------
```

It's fixed with this commit: 
https://github.com/Azure/umock-c/commit/5240448374417fcfe868bf27f67694dde7cc83c6

It gets confusing though because `c-shared` depends on it, and `utpm` depends on it too (through `c-utitlity`).

I honestly wasn't expecting to get a response (at least not so quickly) from you guys. I was throwing this change up there so someone having trouble could see it in the list of PRs.


----------

By the way, keep up the awesome work! Our company is already in the process of migrating to the platform. It's so much simpler than using yocto or buildroot to deploy things.

**Comment by arsing** [comment]
Yeah, that warning is new in gcc 8, so for now you can use gcc 7 instead (`export CC=gcc-7;
export CXX=g++-7`). It's only in test code so it doesn't affect the product itself.

I'm not sure what the procedure is for updating the submodules (@mrohera ?).

We can fix the commit message when we merge it.

**Comment by mrohera** [comment]
Regarding the C-Shared fixes, looks there is newer release of the C-Shared SDK made very recently, we could consider upgrading to address this problem. I will add a task to the backlog.

**Pull request merged**
