### PR TITLE
Change default quickstart Edge CA expiry to 90 days.

### PR DESCRIPTION
**Pull request by arsing**
Also fix some typos in config.toml.edge.template

### CODE REVIEW

**Comment by daprilik** [comment]
might want to change the committer on that commit :wink:

**Review by massand — APPROVED** [review]

**Comment by arsing** [comment]
Whoops. Fixed.

**Review by daprilik — DISMISSED** [review]

**Comment by arsing** [comment]
Oh, apparently we did actually default this to 90 days in 1.1

https://github.com/Azure/iotedge/blame/release/1.1/edgelet/edgelet-core/src/lib.rs#L63

@varunpuranik @micahl Do you want to make this 90 days then?

**Review by gordonwang0 — APPROVED** [review]

**Comment by micahl** [comment]
@arsing ah yes, let's follow suite with 1.1 (change to 90 days).

**Review by daprilik — APPROVED** [review]

**Pull request merged**
