### PR TITLE
Update edgelet to Rust 1.57 and 2021 edition

### PR DESCRIPTION
**Pull request by vadim-kovalyov**
No changes other than fixing clippy issues. 

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request includes a concise summary of the enhancement or bug fix.

### CODE REVIEW

**Comment by arsing** [comment]
(You also need to bump the iot-identity-service dep in the Cargo.lock after https://github.com/Azure/iot-identity-service/pull/335 is merged.)

**Comment by vadim-kovalyov** [comment]
> (You also need to bump the iot-identity-service dep in the Cargo.lock after [Azure/iot-identity-service#335](https://github.com/Azure/iot-identity-service/pull/335) is merged.)

Done

**Comment by arsing** [comment]
Why have you added submodules under edgelet/hsm-sys ? They're not supposed to be there.

**Review by arsing — APPROVED** [review]

**Comment by vadim-kovalyov** [comment]
> Why have you added submodules under edgelet/hsm-sys ? They're not supposed to be there.

I really don't know how that happened and why those submodules creep into my commits.

**Pull request merged**
