### PR TITLE
iotedge: default path to edged should be parsed from environment variable

### PR DESCRIPTION
**Pull request by ef4203**
For non-standard installations of Azure IoT Edge (e.g., where the path to 'edged' is in a different location), this hardcoded path of the 'edged' binary may or may not be present. This change enables package builders for non-standard installations to wrap the binary with the given environment variable. One example would be the Linux distribution NixOS, where all binaries are stored under `/nix/store/...`. Since this change doesn't affect standard installations (e.g., when the environment variable is not set, it defaults), the benefits outweigh the change.

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [ x ] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [ x ] Title of the pull request is clear and informative.
- [ x ] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [ ] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [ ] concise summary of tests added/modified
	- [ x ] local testing done.  

### Draft PRs
- Open the PR in `Draft` mode if it is:
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.

_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and%20why%20vs.%20how%20For%20example%3A%20) for the PR title and description_

### CODE REVIEW

**Comment by arsing** [comment]
This change is fine.

That said, the only thing this path is used for is the version check (`aziot_edged_version.rs`), because that check works by comparing `https://aka.ms/latest-aziot-edge` against `aziot-edged --version`. But `aziot-edged --version` will print the same version as `env!("CARGO_PKG_VERSION")`, so it would be better to just check that and remove this arg entirely. Eg that is what [the i-i-s version of this check](https://github.com/Azure/iot-identity-service/blob/e7af1d5917ef008ccd8f67c07c589d5bbef384df/aziotctl/src/internal/check/checks/aziot_version.rs#L105) does.

**Comment by ef4203** [comment]
@arsing Thank you for the comment. Very true, I actually didn't follow this command that deep. Especially since `iotedge` and `aziot-edged` are shipped in the same package (at least for deb and rpm). However `aziot-edged` uses `VERSION_WITH_SOURCE_VERSION` see [here](https://github.com/Azure/iotedge/blob/e45807aa83909346f16e43b6359c697464290b11/edgelet/edgelet-core/src/lib.rs#L36). Which is a little different that was Azure Identity Service does. However this is my first contribution here, so I don't know all the ins and outs of this code base.

Let me know if there is something I can improve in this pull request or if we can just leave it as proposed.

**Review by arsing — DISMISSED** [review]

**Comment by arsing** [comment]
@damonbarry @yophilav Do you know why CI isn't running?

**Comment by damonbarry** [comment]
> @damonbarry Damon Barry FTE @yophilav Bear Philavastvanid FTE Do you know why CI isn't running?

We tightened up settings for community-contributed PRs, per Microsoft policy. Someone with merge rights needs to review to make sure it's safe, then add a PR comment.

/azp run

**Comment by ef4203** [comment]
I've updated the PR with the code style requirements suggested by the CI. I need someone to restart the CI again

**Review by arsing — APPROVED** [review]

**Comment by ef4203** [comment]
If I understand correctly, someone has to add the "read-to-merge" label, I cannot add any labels.

**Pull request merged**
