### PR TITLE
Parsing result should not depend on system culture.

### PR DESCRIPTION
**Pull request by alaendle**
Fixes test Microsoft.Azure.Devices.Edge.Azure.Monitor.Test.PrometheusMetricParserTest.TestTime on German systems.

Since prometheus refers to https://pkg.go.dev/strconv#ParseFloat for valid value representation, no thousand seperators are allowed and the decimal seperator should always be a '.' - and not a comma.

### CODE REVIEW

**Comment by nimanch** [comment]
@alaendle : Can you briefly describe the problem? Is the change simply to fix a unit test?

**Comment by alaendle** [comment]
@nimanch - Sorry for being so imprecise here. The answer is: Yes (and no 😉). So basically I've expected that a clean checkout of this project runs all unit tests successfully on any machine. However - since the code is sensitive to the machines locale I've got: 

grafik

This is the result of the '.' that is used in Germany to separate thousands - and ',' represents the decimal separator.

However 
https://github.com/Azure/iotedge/blob/9339550b5b267f56f0d198e85cb80e6ab08d7532/edge-modules/azure-monitor/src/PrometheusMetricsParser.cs#L26
indicates that you never expect a thousands separator or a ',' as a decimal separator - so the code used for parsing should reflect these expectations (from my point of view). And this motivated my code change.

Hope things are more clear now. But don't hesitate to contact me if you have further questions.

**Comment by nimanch** [comment]
> @nimanch - Sorry for being so imprecise here. The answer is: Yes (and no 😉). So basically I've expected that a clean checkout of this project runs all unit tests successfully on any machine. However - since the code is sensitive to the machines locale I've got:
> 
> grafik
> 
> This is the result of the '.' that is used in Germany to separate thousands - and ',' represents the decimal separator.
> 
> However
> 
> https://github.com/Azure/iotedge/blob/9339550b5b267f56f0d198e85cb80e6ab08d7532/edge-modules/azure-monitor/src/PrometheusMetricsParser.cs#L26
> 
> 
> indicates that you never expect a thousands separator or a ',' as a decimal separator - so the code used for parsing should reflect these expectations (from my point of view). And this motivated my code change.
> Hope things are more clear now. But don't hesitate to contact me if you have further questions.

Thanks!, Since Prometheus format do not allow a ',' format, would it make sense to fix the unit test then? For example instead of passing 5.678, pass a Invariant Culture representation of 5.678 ?

**Comment by alaendle** [comment]
@nimanch I couldn't agree, the test isn't the problem, since https://github.com/Azure/iotedge/blob/49d47add70cdf8e3cb3b74f8abe34fba2807398e/edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/PrometheusMetricParserTest.cs#L45 is just specifying a correct prometheus metric and so the parser should be able to handle it - regardless of the systems locale settings. So the only way to fix the test is to fix it's locale (e.g. by something similar to https://stackoverflow.com/questions/5001225/c-sharp-how-can-i-force-localization-culture-to-en-us-for-tests-project), but I think that doesn't make sense - since the parsing should be invariant to any locale. No locale dependent metrics representations exist, so why should the implementation suggest that the parsing depends on the systems locale settings?

**Comment by nimanch** [comment]
> @nimanch I couldn't agree, the test isn't the problem, since
> 
> https://github.com/Azure/iotedge/blob/49d47add70cdf8e3cb3b74f8abe34fba2807398e/edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/PrometheusMetricParserTest.cs#L45
> 
> is just specifying a correct prometheus metric and so the parser should be able to handle it - regardless of the systems locale settings. So the only way to fix the test is to fix it's locale (e.g. by something similar to https://stackoverflow.com/questions/5001225/c-sharp-how-can-i-force-localization-culture-to-en-us-for-tests-project), but I think that doesn't make sense - since the parsing should be invariant to any locale. No locale dependent metrics representations exist, so why should the implementation suggest that the parsing depends on the systems locale settings?

Thanks, what I meant was that 

> @nimanch I couldn't agree, the test isn't the problem, since
> 
> https://github.com/Azure/iotedge/blob/49d47add70cdf8e3cb3b74f8abe34fba2807398e/edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/PrometheusMetricParserTest.cs#L45
> 
> is just specifying a correct prometheus metric and so the parser should be able to handle it - regardless of the systems locale settings. So the only way to fix the test is to fix it's locale (e.g. by something similar to https://stackoverflow.com/questions/5001225/c-sharp-how-can-i-force-localization-culture-to-en-us-for-tests-project), but I think that doesn't make sense - since the parsing should be invariant to any locale. No locale dependent metrics representations exist, so why should the implementation suggest that the parsing depends on the systems locale settings?

Makes sense. Thanks!

**Review by nimanch — APPROVED** [review]

**Review by nlcamp — APPROVED** [review]

**Review by micahl — APPROVED** [review]

**Pull request merged**
