### PR TITLE
Prepare for release 1.3.0

### PR DESCRIPTION
**Pull request by arsing**
- Update i-i-s deps to release/1.3 branch.

- Update aziot-edged version to 1.3.0

Co-authored-by: Bear &lt;yophilav@microsoft.com&gt;

### CODE REVIEW

**Review by varunpuranik — APPROVED** [review]

**Review by varunpuranik — DISMISSED** [review]

**Review by gordonwang0 — DISMISSED** [review]

**Review by damonbarry — COMMENTED** [review]
Should this repo point to a commit (or descendant) in i-i-s that changes PACKAGE_VERSION in packages.yaml to something other than `1.3.0~dev`?

**Review by yophilav — DISMISSED** [review]

**Comment by arsing** [comment]
Yes, will update to new commit hash after https://github.com/Azure/iot-identity-service/pull/425 is merged.

**Review by yophilav — APPROVED** [review]

**Comment by arsing** [comment]
Does anyone know what the E2E Checkin job is complaining about?

**Comment by yophilav** [comment]
> Does anyone know what the E2E Checkin job is complaining about?

Looks like it's trying to install edgelet but fails to do so. It looks interesting that it doesn't try download from the Microsoft Prod when the artifact is not downloaded in the prior step. 
https://github.com/Azure/iotedge/blob/main/test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs#L86

@nlcamp  Any thoughts?

**Comment by nlcamp** [comment]
> @nlcamp Any thoughts?

The 'network is down' errors may be another case of transient 1ES agent connectivity issues we've been seeing lately. Otherwise, it could be that the agent image was rebuilt recently and has issues. If retrying the job later/tomorrow doesn't work, we can look into rebuilding the image.

 @and-rewsmith was looking into transient 1ES issues recently and may have some insight.

**Review by yophilav — APPROVED** [review]

**Comment by yophilav** [comment]
@varunpuranik 
Could you please force merge this PR please? 
The checking tests were passing except E2E-checkin which I have manually test in a self-host agent.
The test was passing after the `6fd1ab3` -- we can safely merge the PR.

**Review by yophilav — APPROVED** [review]

**Pull request merged**
