### PR TITLE
Iotedged: HostConfig.Memory should be i64 instead of i32

### PR DESCRIPTION
**Pull request by varunpuranik**
Docker supports long for HostConfig.Memory option, but in iotedged the field is an i32. So making it i64 to accommodate values > 2^32.

### CODE REVIEW

**Comment by veyalla** [comment]
@avranju a Windows customer was trying to use create options to set module memory limit to 4GB and it didn't work.

**Comment by avranju** [comment]
Ah I see. Cool. Wonder if it should be a `u64` then.

**Comment by varunpuranik** [comment]
I checked the dotnet version is long (not ulong). And I don't think memory will ever exceed the i64 range.

**Comment by dsajanice** [comment]
Shouldn't this have been changed in the swagger doc for the container create options?

**Comment by varunpuranik** [comment]
Emm, Sure. Have we been doing that? I thought the Swagger file was obtained from somewhere. But if we are keeping it in sync, I can update the value in the Swagger file as well.

**Pull request merged**
