### PR TITLE
Adding manifest trust bundle in settings & super config

### PR DESCRIPTION
**Pull request by ggjjj**
Adding manifest trust bundle in Settings struct
Adding support for the manifest trust bundle to be in super config

### CODE REVIEW

**Comment by darobs** [comment]
Please make sure workload API version is set:
https://github.com/Azure/iotedge/blob/master/edgelet/edgelet-http/src/version.rs#L6

**Comment by darobs** [comment]
Also, should we update the workload client version for EdgeAgent and EdgeHub?

https://github.com/Azure/iotedge/blob/master/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs#L13

https://github.com/Azure/iotedge/blob/master/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs#L104

**Review by arsing — APPROVED** [review]
Super-config-related changes seem fine to me.

**Review by darobs — APPROVED** [review]
Latest changes look good.

**Review by darobs — APPROVED** [review]
Last set of changes look fine.

**Pull request merged**
