### PR TITLE
Add a by-value comparer for service accounts so we don't update servi…

### PR DESCRIPTION
**Pull request by darobs**
…ce accounts unless they actually change. (#2039)

### CODE REVIEW

**Comment by darobs** [comment]
Cherry-pick commit to merge to PP branch.

**Comment by massand** [comment]
Please create another commit for cherry-pick 08770de454d663420946ee581ddae1a506d4285c by @richma-ms. And merge without squash. Thanks.

**Comment by richma-ms** [comment]
> Cherry-pick [08770de](https://github.com/Azure/iotedge/commit/08770de454d663420946ee581ddae1a506d4285c) too please

I already have it cherry-picked from yesterday.

**Comment by massand** [comment]
Please ensure this branch goes through CI builds and/or rolling build. Thanks!

**Pull request merged**
