### PR TITLE
[release/1.2 cherry pick] [iotedge check] Skip latest version check in nested scenarios (#4461)

### PR DESCRIPTION
**Pull request by daprilik**
Cherry pick into release 1.2. 
Original PR for reference: #4461

### CODE REVIEW

**Review by arsing — APPROVED** [review]

**Comment by daprilik** [comment]
Had to kick the branch to re-run the CI (api-proxy Checkin wasn't firing for whatever reason)

**Review by arsing — APPROVED** [review]
Looks like you still have the same problem though.

**Comment by daprilik** [comment]
Uh oh, that's spooky. Any idea what might be causing it @arsing?

**Comment by arsing** [comment]
Don't know. My PR didn't have a problem with it.

@huguesBouvier added the pipeline, though I don't think it matters when it just isn't running at all.

**Comment by daprilik** [comment]
It's not even giving me the option to "Squash and merge" manually (presumably since "api-proxy Checkin" is one of the "required" checks)

**Review by huguesBouvier — APPROVED** [review]

**Pull request merged**
