### PR TITLE
Mark tests as failed on failure.

### PR DESCRIPTION
**Pull request by vadim-kovalyov**
`continueOnError: true` has one unfortunate side effect - it marks the step as `Warning` instead of `Error`. It can lead to some confusion and inability to easily retry the pipeline.

I'd like to revert the change where we mark failed tests as warnings. If we need any other steps to run after failed tests, we should use `condition: succeededOrFailed()` on those steps.

### CODE REVIEW

**Review by huguesBouvier — COMMENTED** [review]
But isn't there a side effect from removing this too?
"PublishTestResults@2" might not get executed.
In which case PublishTestResults@2 would be useless because only all green runs would get published :).

**Comment by vadim-kovalyov** [comment]
> But isn't there a side effect from removing this too?
> "PublishTestResults@2" might not get executed.
> In which case PublishTestResults@2 would be useless because only all green runs would get published :).

@huguesBouvier This is definitelly something we need to take care. And as far as I can see, that step has `condition: and(succeededOrFailed(), not(variables['Agent.ProxyUrl']))` which means that it should run regardless.

**Review by huguesBouvier — APPROVED** [review]

**Comment by vadim-kovalyov** [comment]
@yophilav, @damonbarry, any feedback on this? do you see any issues?

**Comment by damonbarry** [comment]
> @yophilav Bear Philavastvanid FTE, @damonbarry Damon Barry FTE, any feedback on this? do you see any issues?

This change takes things back to the way I had them originally, so I don't see any problems. 😉

**Review by damonbarry — APPROVED** [review]

**Pull request merged**
