### PR TITLE
Azure/iotedge issue #2306 - cleanup /var/lib/iotedge

### PR DESCRIPTION
**Pull request by gri6507**
PROBLEM STATEMENT:
`apt purge iotedge` causes dpkg: warning: while removing iotedge, directory '/var/lib/iotedge' not empty so not removed

SOLUTION:
Create /var/lib/iotedge in postinst and cleanup in postrm

DETAILS:
For debian, removed creation of /var/lib/iotedge from dirs and moved it
into postinst.

For debian and debian8, remove /var/lib/iotedge in postrm

TESTING:
Built using package.sh for both ubuntu18.04 and debian8. Tested in local ubuntu 18.04 based docker container.

### CODE REVIEW

**Comment by gri6507** [comment]
I'm not sure how to add the automerge_label

**Comment by arsing** [comment]
Do we want to delete `/var/log/iotedge` too? I don't know what Debian convention is.

Actually, with this change, does `apt uninstall` not complain about not deleting `/var/log/iotedge` like it used to complain about `/var/lib/iotedge` before? Or is it that it special-cases directories under `/var/log` ?


>I'm not sure how to add the automerge_label

You can't add the label. Only committers can do that.

**Comment by gri6507** [comment]
> Do we want to delete `/var/log/iotedge` too? I don't know what Debian convention is.
> 
> Actually, with this change, does `apt uninstall` not complain about not deleting `/var/log/iotedge` like it used to complain about `/var/lib/iotedge` before? Or is it that it special-cases directories under `/var/log` ?

It is actually `apt purge` which now does the cleanup of  `/var/lib/iotedge`. With regards to `/var/log/iotedge` cleanup, apparently my testing did not have any logs in that directory because `apt purge` was not complaining about that directory being not empty. However, when I tested the debian behavior in a simple test deb package which puts content in `/var/log/foo`, the act of purging does, in fact, complain that it cannot delete `/var/log/foo` because it is non-empty. So, I am going to update this PullRequest to treat the `/var/log/iotedge` directory in a similar way.

**Comment by arsing** [comment]
Yeah sorry, I meant `apt purge`, not `apt uninstall`.

I couldn't find any search results to confirm where `purge`ing should also delete log files or not. Mike and I talked offline and we think it's fine to do it anyway.

I'll queue up a packages build and test manually, then we can merge this.

**Pull request merged**
