### PR TITLE
Fix license type in aziot-edge.spec

### PR DESCRIPTION
**Pull request by gordonwang0**
Fix typo of license type in aziot-edge.spec.

### CODE REVIEW

**Comment by arsing** [comment]
There's no need to do this here. Do it in i-i-s. The a-i-s package already conflicts with iotedge, so just need to add libiothsm-std to the list.

**Comment by gordonwang0** [comment]
I did it here because aziot-edge is more equivalent to iotedge than a-i-s. It shouldn't be a problem to install a-i-s with iotedge+libiothsm, but installing aziot-edge should remove iotedge+libiothsm.

There's another PR I made in i-i-s that moves the conflict to this package. https://github.com/Azure/iot-identity-service/pull/139

**Comment by arsing** [comment]
>I did it here because aziot-edge is more equivalent to iotedge than a-i-s. It shouldn't be a problem to install a-i-s with iotedge+libiothsm, but installing aziot-edge should remove iotedge+libiothsm.

a-i-s is the equivalent of iotedge because they both do provisioning, and only one should be able to do the provisioning. Installing a-i-s absolutely must remove iotedge. The way it was implemented is correct.

**Comment by gordonwang0** [comment]
Got it. I'll fix it then.

There's a typo in the aziot-edge.spec file for the license. Would still like to fix that.

**Review by arsing — APPROVED** [review]
Update the PR title and OP before kodiak merges it.

**Pull request merged**
