### PR TITLE
Make super config public

### PR DESCRIPTION
**Pull request by lfitchett**
The iotedge_config_cli will use the iotedge super_config to parse and validate the config passed to it.

### CODE REVIEW

**Comment by arsing** [comment]
What is `iotedge_config_cli` and why does it need access to internal types from this repo?

**Comment by lfitchett** [comment]
Its what we renamed the nested_edge_cli to. It creates the certs and configs for nested edge devices.

https://github.com/Azure-Samples/iotedge_config_cli

**Comment by arsing** [comment]
And what's the answer to my second question?

**Comment by lfitchett** [comment]
It creates the configs for each device. It does this by reading in a base config the user provides and replacing certain sections (provisioning, certs, etc) with the generated values. Everything else it keeps the same. It uses the iotedge Config object to do the parsing. This ensures that the configs generated are always valid.

**Comment by arsing** [comment]
If the generated configs aren't valid, `iotedge config apply` will complain. Why does the tool need the type?

**Comment by lfitchett** [comment]
It generates a config for each device and is run on the dev machine. It's important to validate it on creation, because it could be a while before the customer actually installs the generated configs.

**Comment by arsing** [comment]
We should add a `--dry-run` to `iotedge config apply` then. Can you do that instead?

**Comment by arsing** [comment]
I should clarify why I'm against this change. Given that `iotedge_config_cli` is not our code (it's in a samples repo, which makes it equivalent to user code), this is adding a stability requirement to the crate that we can't afford. Also, it will not be in sync with changes to this repo. If the type changes to add some new field, the sample will write the old config until it updates its dep.

I know that the reason this tool exists is because we don't want to add templating logic to `iotedge` itself, so I'm not saying the tool shouldn't exist as a whole. But the tool is still equivalent to external code, so it should not use any interfaces that we don't have stability guarantees for. The structure of the super-config is stable; the code isn't.

**Review by arsing — APPROVED** [review]

**Pull request merged**
