### PR TITLE
Moved hostname section to top of configuration file

### PR DESCRIPTION
**Pull request by HenrikBach1**
Hi,

When debugging configuration files, it is pretty annoying to scroll down to find, which "hostname" or device a configuration belongs to, instead of leaving it at the top of the configuration.

/Henrik

### CODE REVIEW

**Comment by myagley** [comment]
Hi @HenrikBach1. Thanks for the contribution. Can you please help us understand more the issue this is solving?

**Comment by HenrikBach1** [comment]
Hi @myagley. 

The contribution eases determining which host/device the configuration file is for, by placing the hostname section as the first section in the configuration file.

The rational behind this contribution is that, I personally share the same general configuration file across several devices with minor specific changes. 

When debugging the configuration file for a malfunctioned device, it is pretty annoying to scroll down the configuration file to read the hostname section to determine, whether the configuration file is my general shared file or a specific configuration file for the device by reading the hostname section.

Thus placing the hostname section at the top, the time used for and ease to determine, which host/device the configuration file is for is minimal.

/Henrik

**Comment by myagley** [comment]
Hi Henrik.

Thank you for the contribution. However, we've decided to not change the config file format at this time. Our focus is on moving as much of this configuration into the installers as possible and to also introduce a diagnostics tool to help with common config errors.

Thank you.

**Comment by HenrikBach1** [comment]
Hi Mike,

Great. Thanks for your info.

You're welcome.

**Pull request closed without merging**
