### PR TITLE
Windows packaging changes

### PR DESCRIPTION
**Pull request by jiria**
This is a cherry-pick of the following changes from master:
https://github.com/Azure/iotedge/commit/fe99dbb9968e6c61f59c9ef4543ace7a6c0a67c9
https://github.com/Azure/iotedge/commit/3cf21af3c813a6620b4d256e32901aed1942e1e5
https://github.com/Azure/iotedge/commit/8e846eefc182770fbcade138967148c469b21534
https://github.com/Azure/iotedge/commit/067e31ed490e0556cd1d70ab59f65f8d8e549576
https://github.com/Azure/iotedge/commit/462ebc1f5f533ee552d36763a8ef9fc0b635d376
https://github.com/Azure/iotedge/commit/ced642140a2a6ea0c3698bc65614d0fe33eec760

While the following two changes are also touch files created for the new packaging, I do not believe they are required for the release from the packaging point of view and therefore are not being cherry-picked by this PR:
https://github.com/Azure/iotedge/commit/030dba385b88ed5fde3d18a455fe545cf176c581#diff-99c21894c01e014c0db68616af0bded2
https://github.com/Azure/iotedge/commit/f7e820f4447eafd0ebd460b5eb8f93a841b79039#diff-99c21894c01e014c0db68616af0bded2

### CODE REVIEW

**Comment by arsing** [comment]
>While the following two changes are also touch files created for the new packaging, I do not believe they are required for the release from the packaging point of view and therefore are not being cherry-picked by this PR:

Yes, I confirm this.

>030dba3#diff-99c21894c01e014c0db68616af0bded2

This one just changed the line endings. It doesn't need to be cherry-picked.

>f7e820f#diff-99c21894c01e014c0db68616af0bded2

We have not backported `iotedge check` to 1.0.7, so this shouldn't be cherry-picked either.

**Comment by arsing** [comment]
ad41fec507bb91a2e57a07cd32e287ada0ca08d8 will need to be cherry-picked to fix the branch build.

**Comment by jiria** [comment]
Just to note, the Release fail job is not actually fail, it only failed due to using low version number, which was done on purpose. We can rerun that with the proper number.

**Comment by arsing** [comment]
So it's not a blocker to merging this, right? If so, you can go ahead and merge it.

**Comment by jiria** [comment]
Correct.

**Pull request merged**
