### PR TITLE
Ensure edge-agent and edge-hub use logger when logging exception stacktraces

### PR DESCRIPTION
**Pull request by Gunni**
Ensure edge-agent and edge-hub use logger when logging exception stacktraces

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [X] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [X] Title of the pull request is clear and informative.
- [X] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [ ] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [ ] concise summary of tests added/modified
	- [ ] local testing done.

### CODE REVIEW

**Comment by vipeller** [comment]
I think these are good changes, I have one concern, though:

In edgeHub, exceptions will be repeated, which did not happen before. The reason is that edgeHub rethrows exceptions in MainAsync(), while edgeAgent catches them and returns 1. See [here](https://github.com/Azure/iotedge/pull/7213/files#diff-1b89ea51a79ba2ad357d180e178c62c7fe8c3cb747eea655145f13de827e5bebR186).

While edgeAgent has some unguarded code in MainAsync, so the outter try-catch in Main makes sense, in edgeHub that is not very useful at this moment, as edgeHub MainAsync uses a try/catch in its entire body,

I would still prefer this change to make the two codes more uniform, also the outter try/catch in main would protect against future changes in MainAsync, which may let exceptions slip in the future.

However, to avoid duplicated logs, I would recommend to change the re-throw to return 1 (so edgeHub would behave the same as edgeAgent)

**Comment by Gunni** [comment]
@yophilav did you merge in the wrong direction?

**Review by vipeller — APPROVED** [review]

**Review by yophilav — DISMISSED** [review]

**Comment by Gunni** [comment]
@microsoft-github-policy-service agree company="Marel Iceland ehf."

**Comment by Gunni** [comment]
Sorry about my delay, finally got the green flag to accept that CLA, so fine to merge by me.

**Comment by yophilav** [comment]
@Gunni 
It looks like I don't have the push privilege to your branch to fix the coding style. Please see the coding style guide at https://github.com/Azure/iotedge/blob/main/doc/StyleGuide.md . 
Currently the pipelines are failing due to this two errors: 
``` 
../edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs(66,18): error SA1513: Closing brace should be followed by blank line
../edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs(67,18): error SA1513: Closing brace should be followed by blank line
```

**Comment by Gunni** [comment]
@yophilav i gave you access if you want to do it, otherwise I'll do it tomorrow when I have time.

**Review by yophilav — APPROVED** [review]

**Comment by yophilav** [comment]
Alrighty, it's merged. Thank you so much @Gunni for contributing to our project!

**Pull request merged**
