### PR TITLE
Fixed configuration key of the experimental feature flag.

### PR DESCRIPTION
**Pull request by alaendle**
Fixed configuration key of the experimental feature flag (a environment variable called "experimentalFeatures__AddIdentifyingTags" results in the key "experimentalFeatures:AddIdentifyingTags").
https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#environment-variable-configuration-provider

Fixes my previous PR.
https://github.com/Azure/iotedge/pull/6114#discussion_r891470429

### CODE REVIEW

**Comment by alaendle** [comment]
@micahl No, since in edgeHub the query to retrieve the value first asks for the section (experimentalFeatures) and then for the concrete key - but I have used the string to directly access the value, which needs : as a separator.

**Comment by scb01** [comment]
@micahl 

@alaendle is correct in his analysis of how this is handled in the edge hub. We could mimic how hub does this, i.e., create an experimental features class and hold the experimental variables there. However, as we only have a single experimental variable currently, I don't think it is necessary. If we add more, we can refactor the code. The end user experience is not impacted either way, so we should be good.

**Review by scb01 — APPROVED** [review]

**Comment by damonbarry** [comment]
> I'll add @damonbarry as well to this PR so that he can confirm.

@scb01 Direct access of a single experimental variable is fine for now IMO, no need to refactor into a class just yet.

**Comment by micahl** [comment]
#sign-off

**Pull request merged**
