### PR TITLE
[master] Update vulnerable nix version

### PR DESCRIPTION
**Pull request by onalante-msft**
`nix` 0.20.0 was had a memory unsafety vulnerability in `getgrouplist` ([rustsec advisory](https://rustsec.org/advisories/RUSTSEC-2021-0119.html)).  Though we do not use this function internally, this PR updates `nix` to the latest version for simplicity and safety.

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [ ] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [ ] concise summary of tests added/modified
	- [x] local testing done.

### CODE REVIEW

**Comment by arsing** [comment]
`nix` is in edgelet/Cargo.lock too.

**Review by lfitchett — APPROVED** [review]

**Comment by lfitchett** [comment]
> `nix` is in edgelet/Cargo.lock too.

is it a vulnerable version? CG only flags the watchdog crate

**Comment by lfitchett** [comment]
huh, looks like edgelet is using both 0.18.0 and 0.22.0 I wonder why CG didn't flag it?

**Review by lfitchett — CHANGES_REQUESTED** [review]
update edgelet nix as well

**Comment by onalante-msft** [comment]
The http-common update needs to be done in IIS.

**Comment by arsing** [comment]
Also, you should do i-i-s first, then include the i-i-s dep update in this same PR.

**Review by arsing — APPROVED** [review]

**Pull request merged**
