### PR TITLE
Update iot-identity-service and Rust toolchain

### PR DESCRIPTION
**Pull request by gordonwang0**
Updates to the latest iot-identity-service (adds the cloud_timeout_sec and cloud_retries options). Also updates Rust toolchain to 1.52 since that's required to compile the latest iot-identity-service.

### CODE REVIEW

**Comment by gordonwang0** [comment]
Depends on https://github.com/Azure/iot-identity-service/pull/224 first.

**Comment by arsing** [comment]
We can't update the toolchain to 1.52.0 without your tokio 1.0 refactor.

**Comment by gordonwang0** [comment]
Why is that?

**Comment by nyanzebra** [comment]
> Why is that?

Arnav response to my same kind of PR:
https://github.com/Azure/iotedge/pull/5004

**Comment by gordonwang0** [comment]
Ok, I'll move these commits to the refactor branch then. Thanks!

**Pull request closed without merging**
