### PR TITLE
Devguide: Fix and enhance local EdgeHub build

### PR DESCRIPTION
**Pull request by and-rewsmith**
The devguide specified a set of commands to build EdgeHub locally. These stopped working when we made the change to build the rocksdb `.so` file every build. 

To fix this I created two scripts:
1. buildRocksDb.sh: This is the current bash logic in the devops template which builds rocksdb and copies out the binary
2. buildLocalEdgeHub.sh: This uses buildRocksDB.sh, along with another set of scripts to build a local EdgeHub image.

Passing  build (waiting for results):
https://msazure.visualstudio.com/One/_build/results?buildId=51582888&view=results

***Please replace this line with your PR description and read PR checklist below***

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [x] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [x] concise summary of tests added/modified
	- [x] local testing done.  

### Draft PRs
- Open the PR in `Draft` mode if it is:
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.

_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and%20why%20vs.%20how%20For%20example%3A%20) for the PR title and description_

### CODE REVIEW

**Comment by and-rewsmith** [comment]
Waiting for a successful build images run before merge

**Review by darobs — APPROVED** [review]
Thank you for fixing this.

**Comment by nimanch** [comment]
@Seems like the build Images is failing?

**Comment by and-rewsmith** [comment]
Build is fixed. E2E running here to confirm:
https://dev.azure.com/msazure/One/_build/results?buildId=51587632&view=results

**Pull request merged**
