### PR TITLE
Updating cargo lock to pick latest change in iotedge check

### PR DESCRIPTION
**Pull request by huguesBouvier**
Updating cargo lock to pick the following PR: https://github.com/Azure/iot-identity-service/commit/e7c582a0c8b788751a6af99d76558ad7172be2f9

### CODE REVIEW

**Comment by arsing** [comment]
You need to push `release/1.2` branch to include that commit first.

**Review by huguesBouvier — COMMENTED** [review]
I created a PR for it: https://github.com/Azure/iot-identity-service/pull/194#pullrequestreview-625818977
I suspect you directly push from your machine but I can't do it. It fails for me.

**Comment by arsing** [comment]
You needed to push it, yes. Don't merge it manually in the future. I have to disable branch protection to force-push now.

**Comment by arsing** [comment]
Not to mention, what you did was create a new commit, so the commit hash you have here would still be the wrong one.

Anyway, I've fixed the branch now.

**Review by arsing — APPROVED** [review]

**Comment by huguesBouvier** [comment]
> Not to mention, what you did was create a new commit, so the commit hash you have here would still be the wrong one.
> 
> Anyway, I've fixed the branch now.

Yea, sorry I realized it was useless... But one I push I could not roll back.

**Comment by huguesBouvier** [comment]
> Not to mention, what you did was create a new commit, so the commit hash you have here would still be the wrong one.
> 
> Anyway, I've fixed the branch now.

But seems like I can't push

**Pull request merged**
